name: "Bug Report: Script Issues"
description: 🐛 Report issues with generated scripts to enhance privacy.sexy
labels: [ 'bug' ]
title: '[Bug]: '
body:
  -
    type: markdown
    attributes:
      value: |-
        Thank you for contributing to privacy.sexy and guiding our direction! 🌟
        Please complete as much of the form below as possible.
        Your feedback is valuable, even if you can't provide all details.
  -
    type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: >-
        For example: "After running the cleanup script, music playback stopped functioning."
    validations:
      required: true
  -
    type: textarea
    attributes:
      label: How can the bug be recreated?
      description: |-
        This is the most important information in the bug report.
        Bugs that cannot be reproduced cannot be fixed or verified.
      placeholder: |-
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  -
    type: textarea
    attributes:
      label: Operating system
      description: |-
        Please specify your operating system and its version.

        - On Windows: Open "Start button" > "Settings" > "System" > "About".
        - On macOS: Open "Apple menu (top left corner)" > "About This Mac".
        - On Linux: Open terminal > type: lsb_release -a > copy paste the result.
      placeholder: >-
        For example: "Windows 11 Pro 22H3"
    validations:
      required: false
  -
    type: textarea
    attributes:
      label: Script file
      description: |-
        If applicable, share the generated privacy.sexy file.

        GitHub may restrict script file attachments.
        Upload your script file to a service like [GitHub Gist](https://gist.github.com/) and share the link here.

        If you used the desktop version to run the script, it is already stored on your system.
        See the [documentation to locate it](https://github.com/undergroundwires/privacy.sexy/blob/master/docs/desktop/desktop-vs-web-features.md#secure-script-executionstorage).

        > **💡 Tip:** You can attach script files by dragging them into this area.
      placeholder: |-
        Attach the script, or post GitHub Gist link.
        For example: https://gist.github.com/privacysexy-forks/6d85ad8ca27acc8c6a5417d4af28c9b6.
    validations:
      required: false
  -
    type: textarea
    attributes:
      label: Screenshots
      description: |-
        If applicable, add screenshots to help explain your problem.

        > **💡 Tip:** You can attach screenshots by clicking this area to highlight it and then pasting them or dragging files in.
      placeholder: Attach screenshots here or link to image hosting.
    validations:
      required: false
  -
    type: textarea
    attributes:
      label: Additional information
      description: |-
        If applicable, add any other context about the problem here.

        Helpful information includes:

        - Application logs (desktop version only), see: [how to find application logs](https://github.com/undergroundwires/privacy.sexy/blob/master/docs/desktop/desktop-vs-web-features.md#logging).
        - Terminal output
        - Proposed solutions
        - Other related context such as related issues, software behavior, etc.

        > **💡 Tip:** You can attach log files by dragging them into this area.
      placeholder: >-
        For example: "Here are the logs I get from the privacy.sexy 0.13.2 desktop application: ..."
    validations:
      required: false
  -
    type: markdown
    attributes:
      value: |-
        ---

        **✉️ A friendly note from the maintainer:**

        > [!NOTE]
        > We are a small open-source project with a small community.
        > It can sometimes take a long time for issues to be addressed, so please be patient.
        > Consider [donating](https://undergroundwires.dev/donate) to keep privacy.sexy alive and improve support ❤️.
        > But your issue will eventually get attention regardless.
        > <p align="right">@undergroundwires</p>

        ---
