# This file must be named `config.yml`. GitHub does not recognize the file if it is named `config.yaml`.
blank_issues_enabled: true
contact_links:
  - name: Donate
    url: https://undergroundwires.dev/donate/
    about: ❤️ Donate to support the free software you love to keep it alive.
  # A separate link for reporting vulnerabilities is not included here because GitHub generates it automatically.
